# Generated by Django 4.2 on 2023-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='css',
            name='css_file',
            field=models.FileField(upload_to='assets/css'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image_file',
            field=models.FileField(upload_to='assets/images'),
        ),
        migrations.AlterField(
            model_name='jsfile',
            name='javascript_file',
            field=models.FileField(upload_to='assets/js'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='assets/pdf'),
        ),
    ]
