# Generated by Django 4.2 on 2023-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='slug',
            field=models.SlugField(default='j2BQwfP3IiVAHbpT', max_length=30, unique=True),
        ),
    ]
