# Generated by Django 4.2 on 2023-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_imagefile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='slug',
            field=models.SlugField(default='nYsoY6d17PoRw99oQvRkYAZEi9cYfw4Z', max_length=30, unique=True),
        ),
    ]
