# Generated by Django 4.2 on 2023-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_phonemodel_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='unique_id',
            field=models.CharField(default='', max_length=48),
            preserve_default=False,
        ),
    ]
