# Generated by Django 4.2 on 2023-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_phonemodel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='unique_id',
            field=models.CharField(default='', max_length=48),
        ),
    ]
