# Generated by Django 4.2 on 2023-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='wait_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
